export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';

export const SET_CURRENT_FAVORITES = 'SET_CURRENT_FAVORITES';

export const CART_POPUP_SHOW_ACTION = 'CART_POPUP_SHOW_ACTION';
export const ADD_CART_ACTION = 'ADD_CART_ACTION';
export const REMOVE_CART_ACTION = 'REMOVE_CART_ACTION';
export const INCRESE_CART_ACTION = 'INCRESE_CART_ACTION';
export const DECREASE_CART_ACTION = 'DECREASE_CART_ACTION';
